name: Upload Release Asset

on: 
  push:
    tags:
      - 'v*'

jobs:
  build_windows_zip:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
          architecture: 'x64'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install Dev Requirements
      run: pip install -r requirements\requirements-dev.txt
    - name: Run Tests
      run: python -m unittest discover -v
    - name: Build .zip
      run: python devscripts\build.py
    - name: Dump version and release body
      id: dump_version
      run: python devscripts\dump_version.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: plugin.video.picta ${{ steps.dump_version.outputs.version }}
        body: ${{ fromJson(steps.dump_version.outputs.changelog) }}
        draft: false
        prerelease: false
    - name: Upload .zip
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./plugin.video.picta-kodi_19.zip
        asset_name: plugin.video.picta-kodi_19.zip
        asset_content_type: application/x-zip-compressed
    - name: Get SHA2-256SUMS for plugin.video.picta-kodi_19.zip
      id: sha2_file
      run: echo "::set-output name=sha2_windows::$((Get-FileHash plugin.video.picta-kodi_19.zip -Algorithm SHA256).Hash.ToLower())"
    - name: Make SHA2-256SUMS file
      env:
        SHA2_WINDOWS: ${{ steps.sha2_file.outputs.sha2_windows }}
      run: |
        echo "${env:SHA2_WINDOWS}  plugin.video.picta-kodi_19.zip" > SHA2-256SUMS
    - name: Upload SHA2-256SUMS to Release
      id: upload-release-sha2 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./SHA2-256SUMS
        asset_name: SHA2-256SUMS
        asset_content_type: text/plain
